core/urls.py
from apps.authentication.views import *
from django.contrib import admin
from django.urls import path, include 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path('', include("apps.home.routes")),
    path('syi/', see_user_data)
]
urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

apps/home/forms.py
from __future__ import division
from django import forms
from django.forms import ModelForm
from apps.home.models import *


class EtablismentForm  (ModelForm):
      nom=forms.CharField(widget=forms.TextInput( attrs={ "placeholder": "Entre le nom de l'établissement", "class": "form-control"}))
    #   logo=
      site_web= forms.URLField(widget=forms.URLInput(attrs={"placeholder":"Le lien du site de l'établissement", "class":"form-control"}))
      location= forms.ModelChoiceField(queryset=Location.objects.all(), empty_label="Enter la Wilaya de l'etablissment" )
      chef_etablisement= forms.ModelChoiceField(queryset=Researcher.objects.all(), empty_label="Le chef de l'etablissment" )
    #   long_nom=
      long_nom=forms.CharField(widget=forms.TextInput( attrs={ "placeholder": "Entre le nom complet de l'établissement", "class": "form-control"}))
      class Meta:
          model = Etablisment
          fields = ('nom','site_web','location','chef_etablisement','long_nom')


class DivisionForm  (ModelForm):
      nom=forms.CharField(widget=forms.TextInput( attrs={ "placeholder": "Entre le nom de la division", "class": "form-control"}))
    #   logo=
      site_web= forms.URLField(widget=forms.URLInput(attrs={"placeholder":"Le lien du site de la division", "class":"form-control"}))
      etablisment= forms.ModelChoiceField(queryset=Etablisment.objects.all(), empty_label="Enter  l'établissement de la division " )
      chef_div= forms.ModelChoiceField(queryset=Researcher.objects.all(), empty_label="Le chef de l'etablissment" )
    #   long_nom=
      long_nom=forms.CharField(widget=forms.TextInput( attrs={ "placeholder": "Entre le nom complet de la division", "class": "form-control"}))
      class Meta:
          model = Division
          fields = ('nom','site_web','etablisment','chef_div','long_nom')
          
class EquipeForm  (ModelForm):
      nom=forms.CharField(widget=forms.TextInput( attrs={ "placeholder": "Entre le nom de l'équipe", "class": "form-control"}))
    #   logo=
      site_web= forms.URLField(widget=forms.URLInput(attrs={"placeholder":"Le lien du site de l'équipe", "class":"form-control"}))
      division= forms.ModelChoiceField(queryset=Division.objects.all(), empty_label="Enter  la division de l'équipe " )
      chef_equipe= forms.ModelChoiceField(queryset=Researcher.objects.all(), empty_label="Le chef de l'équipe" )
    #   long_nom=
      long_nom=forms.CharField(widget=forms.TextInput( attrs={ "placeholder": "Entre le nom complet de l'équipe", "class": "form-control"}))
      class Meta:
          model = Equipe
          fields = ('nom','site_web','division','chef_equipe','long_nom')

apps/templates/div-liste.html
{%for div,value in divisions.items %}
    <tr>
        <td class="rounded-start">
            {{div}}
        </td>
        <td>
            {{value.chef_div}}
        </td>
        <td>
            {{value.etablisement}}
        </td>
        <td>
            {{value.nbr_equipes}}
        </td>
        <td class="h-12">
            {{value.nbr_chers}}
        </td>
        <td class="rounded-end">
            <a class="btn btn-pill btn-outline-info" href="{%url 'org-div-dash' div_id=div.id%}">consulter</a>
        </td>
        {% if  user.is_superuser %}
        <td>
            <i class="bi bi-box-arrow-up-right"></i>Modifier
        </td>
        <td>
            <a  href="{% url 'org-divs-delete' div.id  %}" type="button" onclick="return confirm( 'vous etes sur de vouloir supprimer la division {{div}} ');"> <i  class="bi bi-trash3"></i> Supprimer</a>
        </td>
        {% endif %}
    </tr>
{%endfor%}

apps/templates/empty.html
{%load static%}


<form action="{%url 'eta-options'%}" method="get">

    <label class="my-1 me-2" for="country">Wilaya</label>
    <select name="wilaya" id="id_wilaya" >
        <option value='0'>Tous</option>
        {%for wilaya in wilayas%}
        <option value="{{wilaya.id}}">{{wilaya}}</option>
        {%endfor%}
    </select>
    <label class="my-1 me-2" for="country">Etablisement</label>
    <select name="wilaya" id="id_etablisment" >
        <option value='0' selected>Tous</option>
        {%for eta in etas%}
        <option value="{{eta.id}}">{{eta}}</option>
        {%endfor%} 
    </select>
</form>

<div class="card border-0 shadow mb-4">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-centered table-nowrap mb-0 rounded align-middle" id="liste">
                <thead class="thead-light align-middle">
                    <tr>
                        <th class="border-0 rounded-start">Nom de Division</th>
                        <th class="border-0">Directeur</th>
                        <th class="border-0">Etablisement assosie</th>
                        <th class="border-0">Nbr Equipe</th>
                        <th class="border-0 ">Nbr Chercheurs</th>
                        <th class="border-0 rounded-end">Tableau de Bord</th>
                        {% if  user.is_superuser %}
                        <th class="border-0 " colspan="2">Action</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody id="div-liste">

                </tbody>
            </table>
        </div>
    </div>
</div>

<p ></p>



{% include 'includes/scripts.html' %}
<script>
    const all_eta = $("#id_etablisment").html()
    $( window ).on( "load",function(){
        $('#id_wilaya').val('0')
        $('#id_etablisment').val('0')
    });

    $('#id_wilaya').change(function(){
        var divs_url= '{%url 'div-ajax-liste'%}';
        $('#id_etablisment').val('0')
        var data = {
            'id_wilaya': $(this).val(),
            'id_etablisment': $('#id_etablisment').val()
        }
        $.ajax({
            url:divs_url,
            data: data,
            success: function(data){
                $('#div-liste').html(data)
            }

        })
        var url = "{% url 'eta-options'%}";
            var id_wiliya = $(this).val();
            if (id_wilaya){
                $.ajax({
                    url:url,
                    data:{
                        'id_wilaya': id_wiliya
                    },
                    success: function(data){
                        $('#id_etablisment').html(data);
                    }
                })
            }
            else{
                $('#id_etablisment').html(all_eta);
            }
    })
    
    $('#id_etablisment').change(function(){
        var divs_url= '{%url 'div-ajax-liste'%}';
        console.log(typeof($(this).val()))
        $.ajax({
            url:divs_url,
            data:{
                'id_wilaya': $('#id_wilaya').val(),
                'id_etablisment': $(this).val(),
            },
            success: function(data){
                console.log(data)
                $('#div-liste').html(data)
            }

        })
    })

</script>

apps/templates/refrech.html
{% extends "layouts/base.html" %} 
{%load static%} 
{% block content %} 
<div class="spinner-border" role="status">
    <span class="sr-only">Loading...</span>
</div>
{% endblock content %} 